/**
 * telegram-bot.js
 *
 * Runs the Telegram bot (long-polling) and its delivery worker inside the
 * same process as the main web server (see server.js), rather than as a
 * separate standalone process. Call startTelegramService() once, after the
 * HTTP server is listening.
 *
 *   1. Handles two kinds of /start deep-links generated by src/lib/memories/*:
 *        - snap_{id}_{token} — one-off scheduled memory (scheduleMemory)
 *        - sub_{id}_{token}  — recurring random-memory subscription
 *      Linking either stores the user's Telegram chat_id on the row.
 *   2. Polls the database every 60s for:
 *        - scheduled memories whose delivery time has arrived
 *        - subscriptions whose frequency/day/time-of-day matches right now
 *      and sends the photo via the Bot API.
 *
 * server.js is expected to have already loaded .env.local (dotenv) before
 * dynamically importing this module, since `db` below connects using
 * process.env.AUTH_DRIZZLE_URL at import time.
 */
import { Bot, InputFile } from 'grammy';
import { db, scheduledMemories, memorySubscriptions } from './schema.js';
import { and, eq, lte, or, lt, isNotNull } from 'drizzle-orm';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const CHECK_INTERVAL_MS = 60_000;
const MAX_RETRIES = 5;
const SGT_OFFSET_MS = 8 * 60 * 60 * 1000;

// src/lib/slides.ts is TypeScript, which this plain module can't import
// directly the way Next.js code can. It's a generated file
// (scripts/generate-slides.mjs) with a stable
// `{ src: getImageUrl('...'), type: '...' }` shape per line, so we parse it
// as text instead of duplicating the MinIO-listing logic here. Read fresh
// each tick (cheap — it's a small file) so newly-uploaded photos are picked
// up without restarting the server.
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SLIDES_SOURCE_PATH = path.join(__dirname, 'lib', 'slides.ts');
const CDN_BASE_URL = 'https://cdn.jactbb.com/it2305-memories';

function loadPhotoSlides() {
  const source = fs.readFileSync(SLIDES_SOURCE_PATH, 'utf-8');
  const entryRegex = /getImageUrl\('([^']+)'\),\s*type:\s*'(image|video)'/g;
  const photos = [];
  let match = entryRegex.exec(source);
  while (match !== null) {
    const [, filename, type] = match;
    if (type === 'image') photos.push({ src: `${CDN_BASE_URL}/${filename}` });
    match = entryRegex.exec(source);
  }
  return photos;
}

// =============================================================================
// Shared helper — download a photo and upload the raw bytes to Telegram.
// sendPhoto-by-URL relies on Telegram's own servers fetching it, which is
// unreliable for anything but small images ("failed to get HTTP URL content"
// is a common, size-sensitive failure even well under the documented limits).
// =============================================================================

async function sendPhotoBytes(bot, chatId, photoSrc, caption) {
  const photoRes = await fetch(photoSrc);
  if (!photoRes.ok) {
    throw new Error(`Failed to download photo: HTTP ${photoRes.status}`);
  }
  const photoBytes = Buffer.from(await photoRes.arrayBuffer());
  const filename = decodeURIComponent(photoSrc.split('/').pop() ?? 'memory.jpg');
  await bot.api.sendPhoto(chatId, new InputFile(photoBytes, filename), { caption });
}

// =============================================================================
// /start command — links a Telegram chat to a scheduled memory or subscription
// =============================================================================

async function linkScheduledMemory(ctx, payload, chatId) {
  const parts = payload.split('_');
  if (parts.length < 2) {
    return ctx.reply('❌ Invalid link. Please use the latest link from your dashboard.');
  }
  const token = parts.pop();
  const id = Number(parts.join('_'));

  if (!Number.isInteger(id)) {
    return ctx.reply('❌ Invalid link. Please use the latest link from your dashboard.');
  }

  try {
    const rows = await db
      .select({
        id: scheduledMemories.id,
        telegramLinkToken: scheduledMemories.telegramLinkToken,
        telegramChatId: scheduledMemories.telegramChatId,
      })
      .from(scheduledMemories)
      .where(eq(scheduledMemories.id, id))
      .limit(1);
    const memory = rows[0];

    if (!memory || memory.telegramLinkToken !== token) {
      return ctx.reply('❌ Invalid or expired link. Please use the correct link from your dashboard.');
    }

    if (memory.telegramChatId) {
      return ctx.reply('✅ This memory is already linked! You\'ll receive it when it\'s time.');
    }

    await db
      .update(scheduledMemories)
      .set({ telegramChatId: String(chatId), deliveryStatus: 'linked' })
      .where(and(eq(scheduledMemories.id, id), eq(scheduledMemories.telegramLinkToken, token)));

    await ctx.reply('✅ Successfully linked!\n\nYou\'ll get a surprise here when the time comes 📸');
  } catch (err) {
    console.error('[telegram-bot] Error linking scheduled memory:', err);
    await ctx.reply('❌ Something went wrong. Please try again later.');
  }
}

async function linkSubscription(ctx, payload, chatId) {
  const parts = payload.split('_');
  if (parts.length < 2) {
    return ctx.reply('❌ Invalid link. Please use the latest link from your dashboard.');
  }
  const token = parts.pop();
  const id = Number(parts.join('_'));

  if (!Number.isInteger(id)) {
    return ctx.reply('❌ Invalid link. Please use the latest link from your dashboard.');
  }

  try {
    const rows = await db
      .select({
        id: memorySubscriptions.id,
        telegramLinkToken: memorySubscriptions.telegramLinkToken,
        telegramChatId: memorySubscriptions.telegramChatId,
        frequency: memorySubscriptions.frequency,
      })
      .from(memorySubscriptions)
      .where(eq(memorySubscriptions.id, id))
      .limit(1);
    const sub = rows[0];

    if (!sub || sub.telegramLinkToken !== token) {
      return ctx.reply('❌ Invalid or expired link. Please use the correct link from your dashboard.');
    }

    if (sub.telegramChatId) {
      return ctx.reply('✅ This subscription is already linked!');
    }

    await db
      .update(memorySubscriptions)
      .set({ telegramChatId: String(chatId) })
      .where(and(eq(memorySubscriptions.id, id), eq(memorySubscriptions.telegramLinkToken, token)));

    await ctx.reply(
      `✅ Subscribed!\n\nYou'll get a random memory ${sub.frequency} 📸`,
    );
  } catch (err) {
    console.error('[telegram-bot] Error linking subscription:', err);
    await ctx.reply('❌ Something went wrong. Please try again later.');
  }
}

// =============================================================================
// Delivery worker — polls for due, linked memories and sends them
// =============================================================================

async function processDueMemories(bot) {
  const now = new Date();

  let due;
  try {
    due = await db
      .select()
      .from(scheduledMemories)
      .where(
        and(
          lte(scheduledMemories.sendAt, now),
          or(
            eq(scheduledMemories.deliveryStatus, 'linked'),
            and(
              eq(scheduledMemories.deliveryStatus, 'failed'),
              lt(scheduledMemories.retryCount, MAX_RETRIES),
            ),
          ),
        ),
      );
  } catch (err) {
    console.error('[telegram-worker] Failed to query due memories:', err);
    return;
  }

  for (const memory of due) {
    try {
      await sendPhotoBytes(
        bot,
        memory.telegramChatId,
        memory.photoSrc,
        memory.caption
          ? `A memory from your past! 🤗\n\n"${memory.caption}"`
          : 'A memory from your past! 🤗',
      );

      await db
        .update(scheduledMemories)
        .set({ deliveryStatus: 'sent', deliveredAt: new Date(), errorMessage: null })
        .where(eq(scheduledMemories.id, memory.id));

      console.log(`[telegram-worker] Sent memory ${memory.id} to chat ${memory.telegramChatId}`);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.error(`[telegram-worker] Failed to send memory ${memory.id}:`, message);

      await db
        .update(scheduledMemories)
        .set({
          deliveryStatus: 'failed',
          errorMessage: message,
          retryCount: memory.retryCount + 1,
        })
        .where(eq(scheduledMemories.id, memory.id));
    }
  }
}

// =============================================================================
// Subscription worker — recurring random-memory sends
// =============================================================================

/** Read a UTC Date's Singapore (UTC+8, no DST) wall-clock components. */
function toSgtParts(date) {
  const sgt = new Date(date.getTime() + SGT_OFFSET_MS);
  return {
    year: sgt.getUTCFullYear(),
    month: sgt.getUTCMonth(),
    date: sgt.getUTCDate(),
    day: sgt.getUTCDay(),
    hhmm: `${String(sgt.getUTCHours()).padStart(2, '0')}:${String(sgt.getUTCMinutes()).padStart(2, '0')}`,
  };
}

function sameSgtCalendarDate(a, b) {
  return a.year === b.year && a.month === b.month && a.date === b.date;
}

function isSubscriptionDue(sub, nowParts) {
  if (nowParts.hhmm !== sub.timeOfDay) return false;
  if (sub.frequency === 'weekly' && nowParts.day !== sub.dayOfWeek) return false;
  if (sub.frequency === 'monthly' && nowParts.date !== sub.dayOfMonth) return false;
  // daily has no extra day condition

  if (sub.lastSentAt && sameSgtCalendarDate(toSgtParts(sub.lastSentAt), nowParts)) {
    return false; // already sent today — guards against re-matching on the next tick
  }
  return true;
}

function pickRandomPhoto(excludeSrc) {
  const photoSlides = loadPhotoSlides();
  const pool = excludeSrc
    ? photoSlides.filter((s) => s.src !== excludeSrc)
    : photoSlides;
  const candidates = pool.length > 0 ? pool : photoSlides;
  return candidates[Math.floor(Math.random() * candidates.length)];
}

async function processDueSubscriptions(bot) {
  const now = new Date();
  const nowParts = toSgtParts(now);

  let active;
  try {
    active = await db
      .select()
      .from(memorySubscriptions)
      .where(and(eq(memorySubscriptions.active, true), isNotNull(memorySubscriptions.telegramChatId)));
  } catch (err) {
    console.error('[telegram-worker] Failed to query subscriptions:', err);
    return;
  }

  for (const sub of active) {
    if (!sub.telegramChatId || !isSubscriptionDue(sub, nowParts)) continue;

    try {
      const photo = pickRandomPhoto(sub.lastSentPhotoSrc);
      await sendPhotoBytes(bot, sub.telegramChatId, photo.src, 'Your random memory! 🎲📸');

      await db
        .update(memorySubscriptions)
        .set({ lastSentAt: now, lastSentPhotoSrc: photo.src })
        .where(eq(memorySubscriptions.id, sub.id));

      console.log(`[telegram-worker] Sent subscription memory ${sub.id} to chat ${sub.telegramChatId}`);
    } catch (err) {
      // Subscriptions have no retry/failed state — just log and try again on the
      // next matching occurrence (tomorrow/next week/next month).
      console.error(`[telegram-worker] Failed to send subscription ${sub.id}:`, err);
    }
  }
}

// =============================================================================
// Startup
// =============================================================================

/**
 * Start the Telegram bot (long-polling) and the 60s delivery-check loop.
 * Safe to call once; logs and no-ops (rather than crashing the web server)
 * if TELEGRAM_BOT_TOKEN isn't configured, so a missing bot token doesn't
 * take the whole site down.
 */
export function startTelegramService() {
  const botToken = process.env.TELEGRAM_BOT_TOKEN;
  if (!botToken) {
    console.error('[telegram-bot] TELEGRAM_BOT_TOKEN not set — Telegram delivery is disabled.');
    return;
  }

  const bot = new Bot(botToken);

  bot.command('start', async (ctx) => {
    const startPayload = ctx.match;
    const chatId = ctx.chat.id;

    if (startPayload && startPayload.startsWith('sub_')) {
      return linkSubscription(ctx, startPayload.slice(4), chatId);
    }
    if (startPayload && startPayload.startsWith('snap_')) {
      return linkScheduledMemory(ctx, startPayload.slice(5), chatId);
    }

    return ctx.reply(
      '👋 Welcome to IT2305 Memories!\n\n'
      + 'To receive your future memory, open the link from your dashboard.',
    );
  });

  bot.catch((err) => {
    console.error('[telegram-bot] Unhandled error:', err);
  });

  // This background loop runs for the lifetime of the web server process, so
  // a transient DB hiccup (e.g. ECONNRESET) must not be allowed to surface as
  // an uncaught exception deep in the `postgres` driver and crash the whole
  // site along with it — log and keep the process alive instead.
  process.on('uncaughtException', (err) => {
    console.error('[telegram-worker] Uncaught exception (process kept alive):', err);
  });
  process.on('unhandledRejection', (err) => {
    console.error('[telegram-worker] Unhandled rejection (process kept alive):', err);
  });

  bot.start({
    onStart: (botInfo) => {
      console.log(`[telegram-bot] Long-polling started as @${botInfo.username}`);
    },
  });

  async function tick() {
    await processDueMemories(bot);
    await processDueSubscriptions(bot);
  }

  setInterval(tick, CHECK_INTERVAL_MS);
  tick();
}
